-- MySQL Script generated by MySQL Workbench
-- Wed Jan 24 20:00:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BD restaurante
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BD restaurante` ;

-- -----------------------------------------------------
-- Schema BD restaurante
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD restaurante` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `BD restaurante` ;

-- -----------------------------------------------------
-- Table `CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CLIENTE` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `CLIENTE` (
  `idCliente` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Fecha_Nacimiento` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `DETALLES FACTURA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DETALLES FACTURA` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `DETALLES FACTURA` (
  `idFactura` INT NOT NULL AUTO_INCREMENT,
  `idProducto` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `Descuento` DECIMAL NOT NULL,
  `Propina` INT NOT NULL,
  PRIMARY KEY (`idFactura`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PRODUCTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PRODUCTOS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PRODUCTOS` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Producto` VARCHAR(45) NOT NULL,
  `Precio_ Producto` DECIMAL NOT NULL,
  `Existencia` INT NOT NULL,
  `Descripcion_producto` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `USUARIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `USUARIO` (
  `idUsuario` INT NOT NULL,
  `Usuario` VARCHAR(60) NOT NULL,
  `Clave` VARCHAR(45) NOT NULL,
  `CLIENTE_idCliente` INT NOT NULL,
  `Perfl_Usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `VENTAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VENTAS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `VENTAS` (
  `idVenta` INT NOT NULL,
  `Fecha_venta` DATE NOT NULL,
  `IdCliente` INT NULL,
  PRIMARY KEY (`idVenta`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
